[project]
name = "file-based-cms"
version = "0.1.0"
description = ""
authors = [
    {name = "nicbencini",email = "nicbencini@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdown (>=3.8,<4.0)",
    "bcrypt (>=4.3.0,<5.0.0)"
]

[tool.poetry]
packages = [{include = "file_based_cms", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
